### ISSUE TITLE
gsva() returns a matrix with fewer gene-sets than the ones that provided with.

### ISSUE THREAD

**Issue by nikolaof** [rcastelo/GSVA#2] opened 2018-03-15 12:28 UTC
Hi.

On my way to run the `gsva()` I created the gene set collection with  the following command from `piano` package

`GSC.C2.msigdb <- loadGSC(file="geneSets/c2.all.v6.1.symbols.gmt", type="gmt")`

After that, I provided it with an expression matrix into the `gsva()` in the following way `gsva_res <- gsva( data, GSC.C2.msigdb$gsc[1:186], mx.diff=FALSE, verbose=TRUE)`

So while initially, I provided it with 186 gene-sets, the result matrix had `dim(gsva_res)` 6 72. Where 72 were my samples and 6, the gene-sets.

`class(GSC.C2.msigdb$gsc)` returns "list"

**Comment by rcastelo** [comment] 2018-03-15 13:29
hi,

it is difficult to diagnose problems without having a full minimal snippet of code that reproduces the situation and without the output of your session information. For this kind of questions about the release version of GSVA it is better to use the support site of Bioconductor at [http://support.bioconductor.org](http://support.bioconductor.org). This issues tab in the GitHub developer site of GSVA is more intended to discuss problems of the development version or ask for new features.

in any case, i'll try to diagnose your problem. gene sets are filtered out when they are formed exclusively by features that are not present in the input expression data. this may happen, for instance, if you are using different kind of gene identifiers between the expression data and the gene set collection. if this is not the case, then you should provide a full reproducible example and the output of the session information and, if this is something happening in the release version of GSVA, i beg you to do it on the Bioconductor support site.

thanks for using GSVA!

**Comment by nikolaof** [comment] 2018-03-15 13:54
So, it seems that the cause of the problem was that the symbols in my expression matrix were in lowercase while in the gene-sets in uppercase.

Sorry for any inconvenience.

**Comment by rcastelo** [comment] 2018-03-15 14:04
good, i'm glad it's solved. i close the issue.

**Closed by rcastelo** 2018-03-15 14:04 UTC

**Comment by shaaaarpy** [comment] 2019-03-21 21:44
Hey 
i have all the gene names in uppercase but still i am getting only 168 gene sets out of 186. How do i determine which gene set i am getting and which gene set is null?

Thank you
