### ISSUE TITLE
Error when runing the function gsva()

### ISSUE THREAD

**Issue by yunbokai** [rcastelo/GSVA#67] opened 2023-01-09 09:12 UTC
Hi,
    I got something wrong when running the function gsva(). Strangely, It seemed that this error occured randomly. Sometimes, the same code ran successfully.

### Here is my gene list:
`gene_features`
str(gene_features)
List of 1
 $ : chr [1:50] "CXCL8" "TMEFF1" "MAGEE1" "CXCL1" ...

### Here is my code:
```
expr <- as.matrix(st.RNA@assays$Spatial@counts)
      es.matrix=GSVA::gsva(expr,
                     gene_features, 
                     kcdf="Poisson",
                     method="ssgsea",
                     abs.ranking=T,
                     parallel.sz=3)
```
st.RNA is my 10X Visium Seurat data

### Get error:
```
Setting parallel calculations through a MulticoreParam back-end
with workers=3 and tasks=100.
Estimating ssGSEA scores for 1 gene sets.
[1] "Calculating ranks..."
[1] "Calculating absolute values from ranks..."
  |                                                                                                  |   0%
Error in d$value$value : $ operator is invalid for atomic vectors
```
### my session
sessionInfo(package = "GSVA")
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
character(0)

other attached packages:
[1] GSVA_1.44.2

Thanks for your help!

**Comment by rcastelo** [comment] 2023-01-09 10:13
Hi, it's difficult to track an error if it can't be reproduced systematically. Could you please show me the output of:

```
dim(expr)
length(gene_features)
```

right before the call to the `gsva()` function, and the output of:

```
traceback()
```

right after the error. By the way, if you use `method="ssgsea"`, the argument `kcdf` is ignore. The parameter `kcdf` is only relevant for the default `method="gsva"`, but I don't think that the error is related to that.

**Comment by yunbokai** [comment] 2023-01-09 10:23
Hi, Thanks for your help 

```
dim(expr)
[1] 18663  3975
length(gene_features)
[1] 1
```
and 
```
traceback()
12: .collect_result(manager, reducer, progress, BPPARAM)
11: .bploop_impl(ITER = ITER, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
        BPOPTIONS = BPOPTIONS, BPREDO = BPREDO, reducer = reducer, 
        progress.length = length(redo_index))
10: bploop.lapply(manager, BPPARAM = BPPARAM, BPOPTIONS = BPOPTIONS, 
        ...)
9: bploop(manager, BPPARAM = BPPARAM, BPOPTIONS = BPOPTIONS, ...)
8: .bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
       BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
7: bplapply(as.list(1:n), function(j) {
       geneRanking <- order(R[, j], decreasing = TRUE)
       es_sample <- lapply(geneSets, .fastRndWalk, geneRanking, 
           j, Ra)
       unlist(es_sample)
   }, BPPARAM = BPPARAM)
6: bplapply(as.list(1:n), function(j) {
       geneRanking <- order(R[, j], decreasing = TRUE)
       es_sample <- lapply(geneSets, .fastRndWalk, geneRanking, 
           j, Ra)
       unlist(es_sample)
   }, BPPARAM = BPPARAM)
5: ssgsea(expr, gset.idx.list, alpha = tau, parallel.sz = parallel.sz, 
       normalization = ssgsea.norm, verbose = verbose, BPPARAM = BPPARAM)
4: .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking, 
       parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose, 
       BPPARAM)
3: .local(expr, gset.idx.list, ...)
2: GSVA::gsva(expr, gene_features, kcdf = "Poisson", method = "ssgsea", 
       abs.ranking = T, parallel.sz = 3)
1: GSVA::gsva(expr, gene_features, kcdf = "Poisson", method = "ssgsea", 
       abs.ranking = T, parallel.sz = 3)
```

**Comment by rcastelo** [comment] 2023-01-09 11:00
My first suspicion was that something may go wrong with just one gene set and performing calculations in parallel, but I've run it in my computer with some mock data and such a setup and found no error. I've noticed that you're running GSVA version 1.44.2, while the current release version is 1.46. Could you try to update the package to the latest release by running:

```
BiocManager::install()
```

and see whether this problem is fixed in the latest release of the software? If updating the software does not fix the problem, then this may be some corner-case for which I'd need to access you data to reproduce the problem in my computer.

**Comment by yunbokai** [comment] 2023-01-09 12:02
I tried my code again, this time I get other Error:

```
Setting parallel calculations through a MulticoreParam back-end
with workers=3 and tasks=100.
Estimating ssGSEA scores for 1 gene sets.
[1] "Calculating ranks..."
[1] "Calculating absolute values from ranks..."
  |==============================================================================   |  97%
Error: BiocParallel errors
  0 remote errors, element index: 
  3565 unevaluated and other errors
  first remote error:
> traceback()
9: stop(.error_bplist(res))
8: .bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
       BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
7: bplapply(as.list(1:n), function(j) {
       geneRanking <- order(R[, j], decreasing = TRUE)
       es_sample <- lapply(geneSets, .fastRndWalk, geneRanking, 
           j, Ra)
       unlist(es_sample)
   }, BPPARAM = BPPARAM)
6: bplapply(as.list(1:n), function(j) {
       geneRanking <- order(R[, j], decreasing = TRUE)
       es_sample <- lapply(geneSets, .fastRndWalk, geneRanking, 
           j, Ra)
       unlist(es_sample)
   }, BPPARAM = BPPARAM)
5: ssgsea(expr, gset.idx.list, alpha = tau, parallel.sz = parallel.sz, 
       normalization = ssgsea.norm, verbose = verbose, BPPARAM = BPPARAM)
4: .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking, 
       parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose, 
       BPPARAM)
3: .local(expr, gset.idx.list, ...)
2: gsva(expr, Angiogenesis_features, kcdf = "Poisson", method = "ssgsea", 
       abs.ranking = T, parallel.sz = 3)
1: gsva(expr, Angiogenesis_features, kcdf = "Poisson", method = "ssgsea", 
       abs.ranking = T, parallel.sz = 3)
```

Due to the reason that my R version is 4.2, I can't update the package right now. But I will try your advice. If the problem still exist, I will upload my data and ask for your help. Thanks again for your attention!

**Comment by rcastelo** [comment] 2023-01-09 14:14
The current release of Bioconductor packages runs on top of R 4.2.x, so in principle, you don't need to update R and you could update the packages, try the following:

```
BiocManager::valid()
```

and it should give you instructions on how to update the packages, otherwise, I think you should be able to do:

```
BiocManager::install(version='3.16')
```
where `version=3.16` is telling the `BiocManager::install()` function to update everything to the current release, which is 3.16.

Another thing you could try is to run the software without parallelism, i.e., `parallel.sz=1`, just in case the problem is with that feature.

**Comment by yunbokai** [comment] 2023-01-10 10:35
Thanks for your kinder reply. Today, I tried my code again before updating the package. The same code worked well. I usually use the R Studio Sever in my lab and this time I ran my code when others got off work. So , I think maybe the problem is with `parallel.sz=3`.

**Comment by rcastelo** [comment] 2023-01-10 13:53
I see, so maybe the error had to do with the failure to allocate 3 threads of parallel execution in a shared server. Anyway, it's always good to work with the last release of the software. I'd like to recommend you next time to post such type of question at the Bioconductor support site at https://support.bioconductor.org using the tag `gsva`, where more people will read it and maybe somebody with a similar problem could give you more useful feedback.

**Closed as completed by rcastelo** 2023-01-10 13:53 UTC
