### ISSUE TITLE
unable to fork, possible reason: Cannot allocate memory when parallel.sz >1

### ISSUE THREAD

**Issue by ditannan** [rcastelo/GSVA#60] opened 2022-03-11 02:33 UTC
the data shape is 40000 (samples) * 2000 (genes), when I using gsva(data, geneset_df, parallel.sz=10, BPPARAM=MulticoreParam(parallel.sz, progressbar=True), I got error:

Error in mcfork(detached) : 
  unable to fork, possible reason: Cannot allocate memory
Calls: gsva ... bploop.iterate -> .send_to -> .send_to -> <Anonymous> -> mcfork
Execution halted
Error while shutting down parallel: unable to terminate some child processes

**Comment by rcastelo** [comment] 2022-04-19 14:35
hi, sorry for the delay in getting back to you. apparently, the problem is that you do not have enough RAM to run such analysis. have you tried to run it in a computer with more RAM or reducing the number of parallel threads?

**Comment by rcastelo** [comment] 2022-05-10 10:18
Since no feedback has been given in the last 3 weeks, I assume the problem has been resolved and I'm closing this issue. If you haven't been able to sort out the problem, I strongly recommend you to use the Bioconductor support site at https://support.bioconductor.org where other developers may also have suggestions about how to address it.

**Closed by rcastelo** 2022-05-10 10:18 UTC
